version: "3"

services:
  mariadb:
    container_name: mariadb
    image: mariadb_img
    build: ./requirements/mariadb/
    restart: always
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception_net

  wordpress:
    container_name: wordpress
    image: wp_img
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    restart: always
    env_file: .env
    volumes:
      - wp:/var/html/wordpress
    networks:
      - inception_net

  nginx:
    container_name: nginx
    image: nginx_img
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    restart: always
    ports:
      - 443:443
    volumes:
      - wp:/var/html/wordpress
    networks:
      - inception_net

volumes:
  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/mfaucheu/data/mariadb_data
  wp:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/mfaucheu/data/wp_data

networks: 
  inception_net:
    driver: bridge
