services:
  db:
    image: postgres:16.9
    container_name: postgres_db
    environment:
      POSTGRES_DB: tennis
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  streamlit:
    build: ./streamlit
    ports:
      - "8501:8501"
    depends_on:
      - db

volumes:
  pgdata:
