services:
  db:
    image: postgres:14.18
    container_name: postgres-tennis
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tennis_streamlit
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pgdata:
